# 扫码枪监控系统配置文件
app:
  name: "Barcode Scanner Monitor"
  version: "2.0.0"
  env: "development" # development, production, test
  debug: true

server:
  host: "localhost"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  type: "sqlite"
  dsn: "./data/scanner.db"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s
  log_level: "info" # silent, error, warn, info

scanner:
  timeout_ms: 100 # 扫码枪输入超时时间（毫秒）
  min_length: 3   # 最小条码长度
  max_length: 50  # 最大条码长度
  enable_hook: true # 是否启用键盘钩子

websocket:
  path: "/ws"
  read_buffer_size: 1024
  write_buffer_size: 1024
  check_origin: true # 是否检查来源
  ping_period: 54s   # ping间隔
  pong_wait: 60s     # pong等待时间
  write_wait: 10s    # 写入等待时间

api:
  prefix: "/api"
  enable_cors: true
  cors_origins:
    - "*"
  rate_limit:
    enable: true
    requests_per_minute: 100

log:
  level: "info" # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file_path: "./logs/app.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days
  compress: true

security:
  enable_auth: false
  jwt_secret: "your-secret-key"
  jwt_expire: 24h
  api_key: "your-api-key"